<center><img src="https://i2.wp.com/hackwagon.com/wp-content/uploads/2017/02/Logo-Web-Export.png?ssl=1" width=200/></center>
<h1> Hackwagon Academy DS102 Lesson 1A </h1>
<h2> Simple Introduction to NumPy</h2> 
<h3> Lesson Outline </h3>

- 1. [What is NumPy](#1)
- 2. [NumPy Array](#2)
    - 2.1 [Creation](#2.1)
    - 2.2 [Manipulation](#2.2)
        - 2.2.1 [Change Datatype](#2.2.1)
        - 2.2.2 [Addition/Subtraction](#2.2.2)
        - 2.2.3 [Multiplication/Division](#2.2.3)
        - 2.2.4 [Boolean Comparison](#2.2.4)
- 3. [Operations](#3)
    - 3.1 [Mathematical & Statistical](#3.1)
    - 3.2 [Uniqueness](#3.2)

In [1]:
!pip install numpy 

<hr/>

<a id='1'><h2><img src="https://images.vexels.com/media/users/3/153978/isolated/preview/483ef8b10a46e28d02293a31570c8c56-warning-sign-colored-stroke-icon-by-vexels.png" width=23 align="left"><font color="salmon">&nbsp;1.</font><font color="salmon"> What is NumPy </font> </h2></a>

NumPy (short for <i>Numerical Python</i>) provides an efficient interface to store and operate dense data. In some ways, NumPy arrays are <b>similar to Python's built in <code>list</code> types</b> but provide much more efficent data storage and data operations! It is because of this versatility, that makes NumPy widely used when to dealing scenarios that require extensive numerical computation, such as Pandas.

Pandas interfaces some of NumPy's core functions and therefore a simple understanding of NumPy will help you a long way in mastering pandas!

<a id='2'><h2><img src="https://images.vexels.com/media/users/3/153978/isolated/preview/483ef8b10a46e28d02293a31570c8c56-warning-sign-colored-stroke-icon-by-vexels.png" width=23 align="left"><font color="salmon">&nbsp;2.</font><font color="salmon"> NumPy Array</font> </h2></a>

In [4]:
import numpy as np

<a id='2.1'><h3>2.1 Creation</h3></a>

You can create new arrays by using `.array()`. You can create an array by using a `list` or a `list` of `list`. 

In [8]:
# Creating arrays with lists
list1 = [1, 3, 4, 7, 11] # 1 x 5
array1 = np.array(list1)
print(array1)
print(type(array1))
list2 = [[2, 4], [12, 14], [22, 24]] # 3 x 2
array2 = np.array(list2)
print(array2)
print(type(array2))

[ 1  3  4  7 11]
<class 'numpy.ndarray'>
[[ 2  4]
 [12 14]
 [22 24]]
<class 'numpy.ndarray'>


<a id='2.2'><h3>2.2 Manipulation</h3></a>

With numpy, comes with the ability to do powerful data manipulation such as the examples below. 

<a id='2.2.1'><h3>2.2.1 Change Datatype</h3></a>

We can change the entire array of values to just 1 data type, by using `.astype()`.

In [7]:
arr1 = np.array([84.837472, 60.99506, 62.602593, 51.28479, 33.769077])
arr1.astype(int)

array([84, 60, 62, 51, 33])

<a id='2.2.2'><h3>2.2.2 Addition/Subtraction</h3></a>

Given two arrays of the <b>same dimensions</b>, we can add/substract values respectively. 

In [9]:
arr_x = np.array([[1, 3], 
                  [7, 5]])
arr_y = np.array([[2, 8], 
                  [16, 4]])

print(arr_x)

print(arr_y)

arr_result = arr_x + arr_y

print(arr_result)

[[1 3]
 [7 5]]
[[ 2  8]
 [16  4]]
[[ 3 11]
 [23  9]]


We can also add/substract the entire array by whatever value we give it

In [10]:
arr_x = np.array([[1, 3], 
                  [7, 5]])
arr_x - 2

array([[-1,  1],
       [ 5,  3]])

<a id='2.2.3'><h3>2.2.3 Multiplication/Divison</h3></a>

Similar to the examples above, we could multiple/divide the arrays respectively.

In [11]:
arr_x = np.array([[1, 3], 
                  [7, 5]])
arr_y = np.array([[2, 8], 
                  [16, 4]])

arr_result = arr_x * arr_y

print(arr_result)

[[  2  24]
 [112  20]]


<a id='2.2.4'><h3>2.2.4 Boolean Comparison</h3></a>

Another powerful feature of NumPy is <b>Boolean Comparison</b>. You can do a conditional check on every value of the array without the need for a for loop. 

In [19]:
arr_x = np.array([[1, 3], 
                  [7, 5]])
arr_y = np.array([[2, 8], 
                  [16, 4]])
arr_x > arr_y

array([[False, False],
       [False,  True]])

<a id='3'><h2><img src="https://images.vexels.com/media/users/3/153978/isolated/preview/483ef8b10a46e28d02293a31570c8c56-warning-sign-colored-stroke-icon-by-vexels.png" width=23 align="left"><font color="salmon">&nbsp;3.</font><font color="salmon"> Operations</font> </h2></a>

<a id='3.1'><h3>3.1 Mathematical & Statistical</h3></a>

NumPy also has the ability to do statistical functions such as `.sum()` or `.mean()`


In [23]:
s = np.array([3, 2, 2, 2])



np.sum(s,0)

9

With a 2-D array, we can also get the sum columns or row wise.

In [18]:
s = np.array([[3, 2, 2, 2],
              [1, 5, 5, 1],
              [2, 2, 3, 5]])

# np.sum(arr, 0) and np.sum(arr, 1) gets the sum of all columns, and rows respectively

np.sum(s,0)
np.sum(s,1)

array([ 9, 12, 12])

<a id='3.2'><h3>3.2 Uniqueness</h3></a>

We can also look for unique values within an array with `.unique()`

In [20]:
# altitudes = np.random.randint(1, 4, (1,6))*1000
altitudes = np.array([20000, 30000, 10000, 20000, 30000, 10000])

np.unique(altitudes)

array([10000, 20000, 30000])